### ISSUE TITLE
Excess encoding of html-entities

### ISSUE THREAD

**Issue by chivorotkiv** [mikenikles/html-to-react#3]
Hi.

If take example from `README.md` then give it following input:

    <span>foo &lt; bar</span>

I expect the same `<span>foo &lt; bar</span>` in output.
But it returns `<span>foo &amp;lt; bar</span>`

**Comment by disquisition** [comment]
I had a similar problem and came to the conclusion that this isn't an issue with `html-to-react`, but rather with [how React handles HTML entities](https://facebook.github.io/react/docs/jsx-gotchas.html#html-entities). You can get around this behavior by using custom processing instructions to decode text nodes:

```js
var HtmlToReact = require('html-to-react');
var React = require('react');
var assert = require('assert');
var decode = require('ent').decode;
var renderToStaticMarkup = require('react-dom/server').renderToStaticMarkup;

var parser = new HtmlToReact.Parser(React);
var processNodeDefinitions = new HtmlToReact.ProcessNodeDefinitions(React);
var instructions = [{
    shouldProcessNode: node => node.type === 'text',
    processNode: node => decode(node.data)
}, {
    shouldProcessNode: () => true,
    processNode: processNodeDefinitions.processDefaultNode
}];

var htmlInput = '<div><h1>Title</h1><p>A paragraph with entities: &amp;&lt;&gt;</p></div>';
var reactComponent = parser.parseWithInstructions(htmlInput, () => true, instructions);
var reactHtml = renderToStaticMarkup(reactComponent);
 
assert.equal(reactHtml, htmlInput);
```

(If, like me, you're used to using Babel to compile JSX, the reason you've never had this problem before is because `babel-plugin-transform-react-jsx` automatically decodes HTML entities in text nodes.)

**Comment by chivorotkiv** [comment]
Hi @disquisition,

Thanks for your note.
Actually I can't reproduce this issue now in v1.0.0. So I'm closing the ticket.
If I meet the problem in future I'll check your instruction. Thank you!
